version: "3"
services:
  nginx:
    image: nginx:1.14.2
    container_name: nginx
    restart: always
    volumes:
      - /home/service/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /zdata/name_project:/zdata/name_project
    ports:
      - 80:80
      - 443:443
    links:
      - api
      - cms
  schedule:
    build:
      context: ./
      dockerfile: /home/service/docker/schedule/Dockerfile
    container_name: schedule
    restart: always
    volumes:
      - /home/service:/home/service
      - /zdata/name_project:/zdata/name_project
      - /home/service/node_modules
    links:
      - es
      - redis
      - mysql
  queue:
    build:
      context: ./
      dockerfile: /home/service/docker/queue/Dockerfile
    restart: always
    volumes:
      - /home/service:/home/service
      - /zdata/name_project:/zdata/name_project
      - /home/service/node_modules
    links:
      - es
      - redis
      - mysql
  api:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    container_name: api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - /home/service:/home/service
      - /zdata/name_project:/zdata/name_project
      - /home/service/node_modules
    links:
      - es
      - redis
      - mysql
  cms:
    build: /home/cms
    container_name: cms
    restart: always
    ports:
      - 4433:4433
    volumes:
      - /home/cms:/home/cms
      - /zdata/name_project:/zdata/name_project
      - /home/cms/node_modules
    links:
      - api
    depends_on:
      - api
    environment:
      - PORT=4433
  es:
    build: /home/service/docker/es
    container_name: es
    volumes:
      - /home/data/es:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200
  redis:
    container_name: redis
    build: /home/service/docker/redis
    volumes:
      - /home/service/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/data/redis:/data
    ports:
      - 6379
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./docker/mysql
      dockerfile: /home/service/docker/mysql/Dockerfile
    environment:
      - MYSQL_DATABASE=crawler
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - TZ=UTC
    volumes:
      - /home/data/mysql:/var/lib/mysql
      - /home/service/docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
